#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ME2U — Database setup script (Ubuntu / WSL)
#
# What this does:
#   1. Checks for Docker (and optionally installs it)
#   2. Starts a PostgreSQL container called me2u-db
#   3. Writes a .env file with DATABASE_URL
#   4. Runs Prisma migrations
#   5. Seeds the database with dev users + sample orders
#
# Usage (from the Backend/ directory):
#   chmod +x scripts/setup-db.sh
#   ./scripts/setup-db.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
DB_NAME="me2u"
DB_USER="me2u_user"
DB_PASS="me2u_secret"
DB_PORT="5432"
CONTAINER="me2u-db"
ENV_FILE="$(dirname "$0")/../.env"

GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

info()  { echo -e "${GREEN}[ME2U]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${RESET} $*"; }
error() { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── 1. Check Docker ───────────────────────────────────────────────────────────
info "Checking for Docker…"
if ! command -v docker &>/dev/null; then
  warn "Docker not found. Installing Docker Engine for Ubuntu…"
  sudo apt-get update -qq
  sudo apt-get install -y ca-certificates curl gnupg lsb-release
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  sudo usermod -aG docker "$USER"
  info "Docker installed. You may need to log out and back in for group changes."
  info "If the next step fails, run: newgrp docker"
fi
info "Docker found: $(docker --version)"

# ── 2. Start (or reuse) the Postgres container ────────────────────────────────
if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  info "Container '${CONTAINER}' is already running — skipping creation."
elif docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  info "Container '${CONTAINER}' exists but is stopped — starting it…"
  docker start "$CONTAINER"
else
  info "Creating Postgres container '${CONTAINER}'…"
  docker run -d \
    --name "$CONTAINER" \
    --restart unless-stopped \
    -e POSTGRES_DB="$DB_NAME" \
    -e POSTGRES_USER="$DB_USER" \
    -e POSTGRES_PASSWORD="$DB_PASS" \
    -p "${DB_PORT}:5432" \
    postgres:16-alpine
  info "Waiting for Postgres to be ready…"
  for i in $(seq 1 20); do
    if docker exec "$CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" &>/dev/null; then
      break
    fi
    sleep 1
  done
fi

# Final readiness check
if ! docker exec "$CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" &>/dev/null; then
  error "Postgres container is not ready after 20 seconds. Try: docker logs ${CONTAINER}"
fi
info "Postgres is ready ✓"

# ── 3. Write .env ─────────────────────────────────────────────────────────────
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:${DB_PORT}/${DB_NAME}"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists — updating DATABASE_URL only."
  # Replace or append DATABASE_URL
  if grep -q "^DATABASE_URL=" "$ENV_FILE"; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=\"${DATABASE_URL}\"|" "$ENV_FILE"
  else
    echo "DATABASE_URL=\"${DATABASE_URL}\"" >> "$ENV_FILE"
  fi
else
  info "Writing .env…"
  cat > "$ENV_FILE" <<EOF
# ME2U — generated by setup-db.sh
DATABASE_URL="${DATABASE_URL}"

# Server
PORT=3001
NODE_ENV=development

# CORS — allow the local frontend served by 'serve'
CORS_ORIGINS="http://localhost:5500,http://localhost:5173"

# Auth (dev mode: use X-User-Id header instead of JWT)
AUTH_DEV_MODE=true

# Auto-release window in hours
AUTO_RELEASE_HOURS=24
EOF
fi
info ".env written ✓"

# ── 4. Install npm dependencies ────────────────────────────────────────────────
info "Installing npm packages…"
cd "$(dirname "$0")/.."
npm install --silent
info "npm install complete ✓"

# ── 5. Run Prisma migrations ──────────────────────────────────────────────────
info "Running Prisma migrations…"
npx prisma migrate dev --name init --skip-seed
info "Migrations applied ✓"

# Generate Prisma client (in case it wasn't generated during install)
npx prisma generate

# ── 6. Seed the database ──────────────────────────────────────────────────────
info "Seeding database…"
npx prisma db seed
info "Seed complete ✓"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}  ME2U database ready!${RESET}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo "  Postgres is running on  → localhost:${DB_PORT}"
echo "  Database                → ${DB_NAME}"
echo "  Connection string       → ${DATABASE_URL}"
echo ""
echo "  Next step — start the API:"
echo "    cd Backend && npm run dev"
echo ""
echo "  Then open the frontend:"
echo "    cd 'Front end' && npx --yes serve -p 5500"
echo "    Open http://localhost:5500/me2u.html"
echo ""
echo "  Useful commands:"
echo "    docker stop ${CONTAINER}     # stop DB"
echo "    docker start ${CONTAINER}    # restart DB"
echo "    npm run db:seed              # re-seed data"
echo "    npx prisma studio            # visual DB browser"
echo ""
